export const ADD_GITHUB_REPOS = 'ADD_GITHUB_REPOS';
export const ADD_GITHUB_ISSUES = 'ADD_GITHUB_ISSUES';
export const API_GITHUB_REQUEST = 'API_GITHUB_REQUEST';
export const API_GITHUB_SUCCESS = 'API_GITHUB_SUCCESS';
export const API_GITHUB_FAILURE = 'API_GITHUB_FAILURE';
